# Generated by Django 3.0.7 on 2022-07-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0002_auto_20220716_1259'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.TextField()),
                ('student_name', models.TextField()),
                ('timeslot', models.TextField()),
                ('subject', models.TextField()),
                ('mentor_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.Mentor')),
                ('student_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
